# Generated by Django 4.2.5 on 2023-10-19 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="creator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
